spring:
  application:
    name: Notiefy
  datasource:
    url: jdbc:postgresql://localhost:5000/notiefy-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
    virtual-host: /

dgs:
  graphql:
    graphiql:
      enabled: true
      path: /graphql

rabbitmq:
  song-added:
      queue: songAdded
      exchange: songAddedExchange
      key: song.added
  song-played:
      queue: songPlayed
      exchange: songPlayedExchange
      key: song.played

server:
  port: 8081
